// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcore

import (
	"database/sql"
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
)

type Roles string

const (
	RolesOwner     Roles = "owner"
	RolesAdmin     Roles = "admin"
	RolesModerator Roles = "moderator"
	RolesStaff     Roles = "staff"
	RolesMember    Roles = "member"
)

func (e *Roles) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Roles(s)
	case string:
		*e = Roles(s)
	default:
		return fmt.Errorf("unsupported scan type for Roles: %T", src)
	}
	return nil
}

type NullRoles struct {
	Roles Roles
	Valid bool // Valid is true if Roles is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoles) Scan(value interface{}) error {
	if value == nil {
		ns.Roles, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Roles.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoles) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Roles), nil
}

type Distributor struct {
	ID        uuid.UUID
	Name      string
	OwnerID   uuid.UUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type DistributorsEmployee struct {
	ID             uuid.UUID
	DistributorsID uuid.UUID
	UserID         uuid.UUID
	Role           Roles
	CreatedAt      sql.NullTime
}
