/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DistributorEmployeeCollectionData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DistributorEmployeeCollectionData{}

// DistributorEmployeeCollectionData struct for DistributorEmployeeCollectionData
type DistributorEmployeeCollectionData struct {
	Type string `json:"type"`
	Attributes []DistributorEmployeeCollectionDataAttributesInner `json:"attributes"`
}

type _DistributorEmployeeCollectionData DistributorEmployeeCollectionData

// NewDistributorEmployeeCollectionData instantiates a new DistributorEmployeeCollectionData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDistributorEmployeeCollectionData(type_ string, attributes []DistributorEmployeeCollectionDataAttributesInner) *DistributorEmployeeCollectionData {
	this := DistributorEmployeeCollectionData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewDistributorEmployeeCollectionDataWithDefaults instantiates a new DistributorEmployeeCollectionData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDistributorEmployeeCollectionDataWithDefaults() *DistributorEmployeeCollectionData {
	this := DistributorEmployeeCollectionData{}
	return &this
}

// GetType returns the Type field value
func (o *DistributorEmployeeCollectionData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *DistributorEmployeeCollectionData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *DistributorEmployeeCollectionData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *DistributorEmployeeCollectionData) GetAttributes() []DistributorEmployeeCollectionDataAttributesInner {
	if o == nil {
		var ret []DistributorEmployeeCollectionDataAttributesInner
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *DistributorEmployeeCollectionData) GetAttributesOk() ([]DistributorEmployeeCollectionDataAttributesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Attributes, true
}

// SetAttributes sets field value
func (o *DistributorEmployeeCollectionData) SetAttributes(v []DistributorEmployeeCollectionDataAttributesInner) {
	o.Attributes = v
}

func (o DistributorEmployeeCollectionData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DistributorEmployeeCollectionData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *DistributorEmployeeCollectionData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDistributorEmployeeCollectionData := _DistributorEmployeeCollectionData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDistributorEmployeeCollectionData)

	if err != nil {
		return err
	}

	*o = DistributorEmployeeCollectionData(varDistributorEmployeeCollectionData)

	return err
}

type NullableDistributorEmployeeCollectionData struct {
	value *DistributorEmployeeCollectionData
	isSet bool
}

func (v NullableDistributorEmployeeCollectionData) Get() *DistributorEmployeeCollectionData {
	return v.value
}

func (v *NullableDistributorEmployeeCollectionData) Set(val *DistributorEmployeeCollectionData) {
	v.value = val
	v.isSet = true
}

func (v NullableDistributorEmployeeCollectionData) IsSet() bool {
	return v.isSet
}

func (v *NullableDistributorEmployeeCollectionData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDistributorEmployeeCollectionData(val *DistributorEmployeeCollectionData) *NullableDistributorEmployeeCollectionData {
	return &NullableDistributorEmployeeCollectionData{value: val, isSet: true}
}

func (v NullableDistributorEmployeeCollectionData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDistributorEmployeeCollectionData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


