/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the EmployeeCreateDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmployeeCreateDataAttributes{}

// EmployeeCreateDataAttributes struct for EmployeeCreateDataAttributes
type EmployeeCreateDataAttributes struct {
	// User ID
	UserId string `json:"user_id"`
	// User role
	Role string `json:"role"`
	// Creation date
	CreatedAt time.Time `json:"created_at"`
}

type _EmployeeCreateDataAttributes EmployeeCreateDataAttributes

// NewEmployeeCreateDataAttributes instantiates a new EmployeeCreateDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmployeeCreateDataAttributes(userId string, role string, createdAt time.Time) *EmployeeCreateDataAttributes {
	this := EmployeeCreateDataAttributes{}
	this.UserId = userId
	this.Role = role
	this.CreatedAt = createdAt
	return &this
}

// NewEmployeeCreateDataAttributesWithDefaults instantiates a new EmployeeCreateDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmployeeCreateDataAttributesWithDefaults() *EmployeeCreateDataAttributes {
	this := EmployeeCreateDataAttributes{}
	return &this
}

// GetUserId returns the UserId field value
func (o *EmployeeCreateDataAttributes) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *EmployeeCreateDataAttributes) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *EmployeeCreateDataAttributes) SetUserId(v string) {
	o.UserId = v
}

// GetRole returns the Role field value
func (o *EmployeeCreateDataAttributes) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *EmployeeCreateDataAttributes) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *EmployeeCreateDataAttributes) SetRole(v string) {
	o.Role = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *EmployeeCreateDataAttributes) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *EmployeeCreateDataAttributes) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *EmployeeCreateDataAttributes) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o EmployeeCreateDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmployeeCreateDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user_id"] = o.UserId
	toSerialize["role"] = o.Role
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *EmployeeCreateDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user_id",
		"role",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmployeeCreateDataAttributes := _EmployeeCreateDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmployeeCreateDataAttributes)

	if err != nil {
		return err
	}

	*o = EmployeeCreateDataAttributes(varEmployeeCreateDataAttributes)

	return err
}

type NullableEmployeeCreateDataAttributes struct {
	value *EmployeeCreateDataAttributes
	isSet bool
}

func (v NullableEmployeeCreateDataAttributes) Get() *EmployeeCreateDataAttributes {
	return v.value
}

func (v *NullableEmployeeCreateDataAttributes) Set(val *EmployeeCreateDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableEmployeeCreateDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableEmployeeCreateDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmployeeCreateDataAttributes(val *EmployeeCreateDataAttributes) *NullableEmployeeCreateDataAttributes {
	return &NullableEmployeeCreateDataAttributes{value: val, isSet: true}
}

func (v NullableEmployeeCreateDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmployeeCreateDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


