/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PlaceEmployeeCollectionData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlaceEmployeeCollectionData{}

// PlaceEmployeeCollectionData struct for PlaceEmployeeCollectionData
type PlaceEmployeeCollectionData struct {
	Type string `json:"type"`
	Attributes []PlaceEmployeeCollectionDataAttributesInner `json:"attributes"`
}

type _PlaceEmployeeCollectionData PlaceEmployeeCollectionData

// NewPlaceEmployeeCollectionData instantiates a new PlaceEmployeeCollectionData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlaceEmployeeCollectionData(type_ string, attributes []PlaceEmployeeCollectionDataAttributesInner) *PlaceEmployeeCollectionData {
	this := PlaceEmployeeCollectionData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewPlaceEmployeeCollectionDataWithDefaults instantiates a new PlaceEmployeeCollectionData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlaceEmployeeCollectionDataWithDefaults() *PlaceEmployeeCollectionData {
	this := PlaceEmployeeCollectionData{}
	return &this
}

// GetType returns the Type field value
func (o *PlaceEmployeeCollectionData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PlaceEmployeeCollectionData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PlaceEmployeeCollectionData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *PlaceEmployeeCollectionData) GetAttributes() []PlaceEmployeeCollectionDataAttributesInner {
	if o == nil {
		var ret []PlaceEmployeeCollectionDataAttributesInner
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *PlaceEmployeeCollectionData) GetAttributesOk() ([]PlaceEmployeeCollectionDataAttributesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Attributes, true
}

// SetAttributes sets field value
func (o *PlaceEmployeeCollectionData) SetAttributes(v []PlaceEmployeeCollectionDataAttributesInner) {
	o.Attributes = v
}

func (o PlaceEmployeeCollectionData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlaceEmployeeCollectionData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *PlaceEmployeeCollectionData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlaceEmployeeCollectionData := _PlaceEmployeeCollectionData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPlaceEmployeeCollectionData)

	if err != nil {
		return err
	}

	*o = PlaceEmployeeCollectionData(varPlaceEmployeeCollectionData)

	return err
}

type NullablePlaceEmployeeCollectionData struct {
	value *PlaceEmployeeCollectionData
	isSet bool
}

func (v NullablePlaceEmployeeCollectionData) Get() *PlaceEmployeeCollectionData {
	return v.value
}

func (v *NullablePlaceEmployeeCollectionData) Set(val *PlaceEmployeeCollectionData) {
	v.value = val
	v.isSet = true
}

func (v NullablePlaceEmployeeCollectionData) IsSet() bool {
	return v.isSet
}

func (v *NullablePlaceEmployeeCollectionData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlaceEmployeeCollectionData(val *PlaceEmployeeCollectionData) *NullablePlaceEmployeeCollectionData {
	return &NullablePlaceEmployeeCollectionData{value: val, isSet: true}
}

func (v NullablePlaceEmployeeCollectionData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlaceEmployeeCollectionData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


