/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Distributor type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Distributor{}

// Distributor struct for Distributor
type Distributor struct {
	Data DistributorData `json:"data"`
}

type _Distributor Distributor

// NewDistributor instantiates a new Distributor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDistributor(data DistributorData) *Distributor {
	this := Distributor{}
	this.Data = data
	return &this
}

// NewDistributorWithDefaults instantiates a new Distributor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDistributorWithDefaults() *Distributor {
	this := Distributor{}
	return &this
}

// GetData returns the Data field value
func (o *Distributor) GetData() DistributorData {
	if o == nil {
		var ret DistributorData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *Distributor) GetDataOk() (*DistributorData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *Distributor) SetData(v DistributorData) {
	o.Data = v
}

func (o Distributor) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Distributor) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *Distributor) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDistributor := _Distributor{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDistributor)

	if err != nil {
		return err
	}

	*o = Distributor(varDistributor)

	return err
}

type NullableDistributor struct {
	value *Distributor
	isSet bool
}

func (v NullableDistributor) Get() *Distributor {
	return v.value
}

func (v *NullableDistributor) Set(val *Distributor) {
	v.value = val
	v.isSet = true
}

func (v NullableDistributor) IsSet() bool {
	return v.isSet
}

func (v *NullableDistributor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDistributor(val *Distributor) *NullableDistributor {
	return &NullableDistributor{value: val, isSet: true}
}

func (v NullableDistributor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDistributor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


