/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DistributorEmployeeDeleteData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DistributorEmployeeDeleteData{}

// DistributorEmployeeDeleteData struct for DistributorEmployeeDeleteData
type DistributorEmployeeDeleteData struct {
	Type string `json:"type"`
	Attributes DistributorEmployeeDeleteDataAttributes `json:"attributes"`
}

type _DistributorEmployeeDeleteData DistributorEmployeeDeleteData

// NewDistributorEmployeeDeleteData instantiates a new DistributorEmployeeDeleteData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDistributorEmployeeDeleteData(type_ string, attributes DistributorEmployeeDeleteDataAttributes) *DistributorEmployeeDeleteData {
	this := DistributorEmployeeDeleteData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewDistributorEmployeeDeleteDataWithDefaults instantiates a new DistributorEmployeeDeleteData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDistributorEmployeeDeleteDataWithDefaults() *DistributorEmployeeDeleteData {
	this := DistributorEmployeeDeleteData{}
	return &this
}

// GetType returns the Type field value
func (o *DistributorEmployeeDeleteData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *DistributorEmployeeDeleteData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *DistributorEmployeeDeleteData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *DistributorEmployeeDeleteData) GetAttributes() DistributorEmployeeDeleteDataAttributes {
	if o == nil {
		var ret DistributorEmployeeDeleteDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *DistributorEmployeeDeleteData) GetAttributesOk() (*DistributorEmployeeDeleteDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *DistributorEmployeeDeleteData) SetAttributes(v DistributorEmployeeDeleteDataAttributes) {
	o.Attributes = v
}

func (o DistributorEmployeeDeleteData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DistributorEmployeeDeleteData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *DistributorEmployeeDeleteData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDistributorEmployeeDeleteData := _DistributorEmployeeDeleteData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDistributorEmployeeDeleteData)

	if err != nil {
		return err
	}

	*o = DistributorEmployeeDeleteData(varDistributorEmployeeDeleteData)

	return err
}

type NullableDistributorEmployeeDeleteData struct {
	value *DistributorEmployeeDeleteData
	isSet bool
}

func (v NullableDistributorEmployeeDeleteData) Get() *DistributorEmployeeDeleteData {
	return v.value
}

func (v *NullableDistributorEmployeeDeleteData) Set(val *DistributorEmployeeDeleteData) {
	v.value = val
	v.isSet = true
}

func (v NullableDistributorEmployeeDeleteData) IsSet() bool {
	return v.isSet
}

func (v *NullableDistributorEmployeeDeleteData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDistributorEmployeeDeleteData(val *DistributorEmployeeDeleteData) *NullableDistributorEmployeeDeleteData {
	return &NullableDistributorEmployeeDeleteData{value: val, isSet: true}
}

func (v NullableDistributorEmployeeDeleteData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDistributorEmployeeDeleteData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


