/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DistributorData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DistributorData{}

// DistributorData struct for DistributorData
type DistributorData struct {
	// Resource ID
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes DistributorDataAttributes `json:"attributes"`
}

type _DistributorData DistributorData

// NewDistributorData instantiates a new DistributorData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDistributorData(id string, type_ string, attributes DistributorDataAttributes) *DistributorData {
	this := DistributorData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewDistributorDataWithDefaults instantiates a new DistributorData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDistributorDataWithDefaults() *DistributorData {
	this := DistributorData{}
	return &this
}

// GetId returns the Id field value
func (o *DistributorData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DistributorData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DistributorData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *DistributorData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *DistributorData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *DistributorData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *DistributorData) GetAttributes() DistributorDataAttributes {
	if o == nil {
		var ret DistributorDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *DistributorData) GetAttributesOk() (*DistributorDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *DistributorData) SetAttributes(v DistributorDataAttributes) {
	o.Attributes = v
}

func (o DistributorData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DistributorData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *DistributorData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDistributorData := _DistributorData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDistributorData)

	if err != nil {
		return err
	}

	*o = DistributorData(varDistributorData)

	return err
}

type NullableDistributorData struct {
	value *DistributorData
	isSet bool
}

func (v NullableDistributorData) Get() *DistributorData {
	return v.value
}

func (v *NullableDistributorData) Set(val *DistributorData) {
	v.value = val
	v.isSet = true
}

func (v NullableDistributorData) IsSet() bool {
	return v.isSet
}

func (v *NullableDistributorData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDistributorData(val *DistributorData) *NullableDistributorData {
	return &NullableDistributorData{value: val, isSet: true}
}

func (v NullableDistributorData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDistributorData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


