/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DistributorEmployeeCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DistributorEmployeeCreate{}

// DistributorEmployeeCreate struct for DistributorEmployeeCreate
type DistributorEmployeeCreate struct {
	Data DistributorEmployeeCreateData `json:"data"`
}

type _DistributorEmployeeCreate DistributorEmployeeCreate

// NewDistributorEmployeeCreate instantiates a new DistributorEmployeeCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDistributorEmployeeCreate(data DistributorEmployeeCreateData) *DistributorEmployeeCreate {
	this := DistributorEmployeeCreate{}
	this.Data = data
	return &this
}

// NewDistributorEmployeeCreateWithDefaults instantiates a new DistributorEmployeeCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDistributorEmployeeCreateWithDefaults() *DistributorEmployeeCreate {
	this := DistributorEmployeeCreate{}
	return &this
}

// GetData returns the Data field value
func (o *DistributorEmployeeCreate) GetData() DistributorEmployeeCreateData {
	if o == nil {
		var ret DistributorEmployeeCreateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DistributorEmployeeCreate) GetDataOk() (*DistributorEmployeeCreateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DistributorEmployeeCreate) SetData(v DistributorEmployeeCreateData) {
	o.Data = v
}

func (o DistributorEmployeeCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DistributorEmployeeCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DistributorEmployeeCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDistributorEmployeeCreate := _DistributorEmployeeCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDistributorEmployeeCreate)

	if err != nil {
		return err
	}

	*o = DistributorEmployeeCreate(varDistributorEmployeeCreate)

	return err
}

type NullableDistributorEmployeeCreate struct {
	value *DistributorEmployeeCreate
	isSet bool
}

func (v NullableDistributorEmployeeCreate) Get() *DistributorEmployeeCreate {
	return v.value
}

func (v *NullableDistributorEmployeeCreate) Set(val *DistributorEmployeeCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableDistributorEmployeeCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableDistributorEmployeeCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDistributorEmployeeCreate(val *DistributorEmployeeCreate) *NullableDistributorEmployeeCreate {
	return &NullableDistributorEmployeeCreate{value: val, isSet: true}
}

func (v NullableDistributorEmployeeCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDistributorEmployeeCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


