/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PlaceEmployeeData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlaceEmployeeData{}

// PlaceEmployeeData struct for PlaceEmployeeData
type PlaceEmployeeData struct {
	// employee ID
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes PlaceEmployeeDataAttributes `json:"attributes"`
}

type _PlaceEmployeeData PlaceEmployeeData

// NewPlaceEmployeeData instantiates a new PlaceEmployeeData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlaceEmployeeData(id string, type_ string, attributes PlaceEmployeeDataAttributes) *PlaceEmployeeData {
	this := PlaceEmployeeData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewPlaceEmployeeDataWithDefaults instantiates a new PlaceEmployeeData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlaceEmployeeDataWithDefaults() *PlaceEmployeeData {
	this := PlaceEmployeeData{}
	return &this
}

// GetId returns the Id field value
func (o *PlaceEmployeeData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PlaceEmployeeData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PlaceEmployeeData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *PlaceEmployeeData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PlaceEmployeeData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PlaceEmployeeData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *PlaceEmployeeData) GetAttributes() PlaceEmployeeDataAttributes {
	if o == nil {
		var ret PlaceEmployeeDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *PlaceEmployeeData) GetAttributesOk() (*PlaceEmployeeDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *PlaceEmployeeData) SetAttributes(v PlaceEmployeeDataAttributes) {
	o.Attributes = v
}

func (o PlaceEmployeeData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlaceEmployeeData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *PlaceEmployeeData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlaceEmployeeData := _PlaceEmployeeData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPlaceEmployeeData)

	if err != nil {
		return err
	}

	*o = PlaceEmployeeData(varPlaceEmployeeData)

	return err
}

type NullablePlaceEmployeeData struct {
	value *PlaceEmployeeData
	isSet bool
}

func (v NullablePlaceEmployeeData) Get() *PlaceEmployeeData {
	return v.value
}

func (v *NullablePlaceEmployeeData) Set(val *PlaceEmployeeData) {
	v.value = val
	v.isSet = true
}

func (v NullablePlaceEmployeeData) IsSet() bool {
	return v.isSet
}

func (v *NullablePlaceEmployeeData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlaceEmployeeData(val *PlaceEmployeeData) *NullablePlaceEmployeeData {
	return &NullablePlaceEmployeeData{value: val, isSet: true}
}

func (v NullablePlaceEmployeeData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlaceEmployeeData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


