/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PlaceEmployeeCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlaceEmployeeCreate{}

// PlaceEmployeeCreate struct for PlaceEmployeeCreate
type PlaceEmployeeCreate struct {
	Data PlaceEmployeeCreateData `json:"data"`
}

type _PlaceEmployeeCreate PlaceEmployeeCreate

// NewPlaceEmployeeCreate instantiates a new PlaceEmployeeCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlaceEmployeeCreate(data PlaceEmployeeCreateData) *PlaceEmployeeCreate {
	this := PlaceEmployeeCreate{}
	this.Data = data
	return &this
}

// NewPlaceEmployeeCreateWithDefaults instantiates a new PlaceEmployeeCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlaceEmployeeCreateWithDefaults() *PlaceEmployeeCreate {
	this := PlaceEmployeeCreate{}
	return &this
}

// GetData returns the Data field value
func (o *PlaceEmployeeCreate) GetData() PlaceEmployeeCreateData {
	if o == nil {
		var ret PlaceEmployeeCreateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PlaceEmployeeCreate) GetDataOk() (*PlaceEmployeeCreateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *PlaceEmployeeCreate) SetData(v PlaceEmployeeCreateData) {
	o.Data = v
}

func (o PlaceEmployeeCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlaceEmployeeCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *PlaceEmployeeCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlaceEmployeeCreate := _PlaceEmployeeCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPlaceEmployeeCreate)

	if err != nil {
		return err
	}

	*o = PlaceEmployeeCreate(varPlaceEmployeeCreate)

	return err
}

type NullablePlaceEmployeeCreate struct {
	value *PlaceEmployeeCreate
	isSet bool
}

func (v NullablePlaceEmployeeCreate) Get() *PlaceEmployeeCreate {
	return v.value
}

func (v *NullablePlaceEmployeeCreate) Set(val *PlaceEmployeeCreate) {
	v.value = val
	v.isSet = true
}

func (v NullablePlaceEmployeeCreate) IsSet() bool {
	return v.isSet
}

func (v *NullablePlaceEmployeeCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlaceEmployeeCreate(val *PlaceEmployeeCreate) *NullablePlaceEmployeeCreate {
	return &NullablePlaceEmployeeCreate{value: val, isSet: true}
}

func (v NullablePlaceEmployeeCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlaceEmployeeCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


