/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DistributorEmployeeCreateDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DistributorEmployeeCreateDataAttributes{}

// DistributorEmployeeCreateDataAttributes struct for DistributorEmployeeCreateDataAttributes
type DistributorEmployeeCreateDataAttributes struct {
	Username string `json:"username"`
	// role for user
	Role string `json:"role"`
}

type _DistributorEmployeeCreateDataAttributes DistributorEmployeeCreateDataAttributes

// NewDistributorEmployeeCreateDataAttributes instantiates a new DistributorEmployeeCreateDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDistributorEmployeeCreateDataAttributes(username string, role string) *DistributorEmployeeCreateDataAttributes {
	this := DistributorEmployeeCreateDataAttributes{}
	this.Username = username
	this.Role = role
	return &this
}

// NewDistributorEmployeeCreateDataAttributesWithDefaults instantiates a new DistributorEmployeeCreateDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDistributorEmployeeCreateDataAttributesWithDefaults() *DistributorEmployeeCreateDataAttributes {
	this := DistributorEmployeeCreateDataAttributes{}
	return &this
}

// GetUsername returns the Username field value
func (o *DistributorEmployeeCreateDataAttributes) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *DistributorEmployeeCreateDataAttributes) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *DistributorEmployeeCreateDataAttributes) SetUsername(v string) {
	o.Username = v
}

// GetRole returns the Role field value
func (o *DistributorEmployeeCreateDataAttributes) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *DistributorEmployeeCreateDataAttributes) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *DistributorEmployeeCreateDataAttributes) SetRole(v string) {
	o.Role = v
}

func (o DistributorEmployeeCreateDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DistributorEmployeeCreateDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["username"] = o.Username
	toSerialize["role"] = o.Role
	return toSerialize, nil
}

func (o *DistributorEmployeeCreateDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"username",
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDistributorEmployeeCreateDataAttributes := _DistributorEmployeeCreateDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDistributorEmployeeCreateDataAttributes)

	if err != nil {
		return err
	}

	*o = DistributorEmployeeCreateDataAttributes(varDistributorEmployeeCreateDataAttributes)

	return err
}

type NullableDistributorEmployeeCreateDataAttributes struct {
	value *DistributorEmployeeCreateDataAttributes
	isSet bool
}

func (v NullableDistributorEmployeeCreateDataAttributes) Get() *DistributorEmployeeCreateDataAttributes {
	return v.value
}

func (v *NullableDistributorEmployeeCreateDataAttributes) Set(val *DistributorEmployeeCreateDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableDistributorEmployeeCreateDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableDistributorEmployeeCreateDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDistributorEmployeeCreateDataAttributes(val *DistributorEmployeeCreateDataAttributes) *NullableDistributorEmployeeCreateDataAttributes {
	return &NullableDistributorEmployeeCreateDataAttributes{value: val, isSet: true}
}

func (v NullableDistributorEmployeeCreateDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDistributorEmployeeCreateDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


