/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DistributorEmployeeUpdateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DistributorEmployeeUpdateData{}

// DistributorEmployeeUpdateData struct for DistributorEmployeeUpdateData
type DistributorEmployeeUpdateData struct {
	Type string `json:"type"`
	Attributes DistributorEmployeeUpdateDataAttributes `json:"attributes"`
}

type _DistributorEmployeeUpdateData DistributorEmployeeUpdateData

// NewDistributorEmployeeUpdateData instantiates a new DistributorEmployeeUpdateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDistributorEmployeeUpdateData(type_ string, attributes DistributorEmployeeUpdateDataAttributes) *DistributorEmployeeUpdateData {
	this := DistributorEmployeeUpdateData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewDistributorEmployeeUpdateDataWithDefaults instantiates a new DistributorEmployeeUpdateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDistributorEmployeeUpdateDataWithDefaults() *DistributorEmployeeUpdateData {
	this := DistributorEmployeeUpdateData{}
	return &this
}

// GetType returns the Type field value
func (o *DistributorEmployeeUpdateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *DistributorEmployeeUpdateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *DistributorEmployeeUpdateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *DistributorEmployeeUpdateData) GetAttributes() DistributorEmployeeUpdateDataAttributes {
	if o == nil {
		var ret DistributorEmployeeUpdateDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *DistributorEmployeeUpdateData) GetAttributesOk() (*DistributorEmployeeUpdateDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *DistributorEmployeeUpdateData) SetAttributes(v DistributorEmployeeUpdateDataAttributes) {
	o.Attributes = v
}

func (o DistributorEmployeeUpdateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DistributorEmployeeUpdateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *DistributorEmployeeUpdateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDistributorEmployeeUpdateData := _DistributorEmployeeUpdateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDistributorEmployeeUpdateData)

	if err != nil {
		return err
	}

	*o = DistributorEmployeeUpdateData(varDistributorEmployeeUpdateData)

	return err
}

type NullableDistributorEmployeeUpdateData struct {
	value *DistributorEmployeeUpdateData
	isSet bool
}

func (v NullableDistributorEmployeeUpdateData) Get() *DistributorEmployeeUpdateData {
	return v.value
}

func (v *NullableDistributorEmployeeUpdateData) Set(val *DistributorEmployeeUpdateData) {
	v.value = val
	v.isSet = true
}

func (v NullableDistributorEmployeeUpdateData) IsSet() bool {
	return v.isSet
}

func (v *NullableDistributorEmployeeUpdateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDistributorEmployeeUpdateData(val *DistributorEmployeeUpdateData) *NullableDistributorEmployeeUpdateData {
	return &NullableDistributorEmployeeUpdateData{value: val, isSet: true}
}

func (v NullableDistributorEmployeeUpdateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDistributorEmployeeUpdateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


