/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DistributorEmployee type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DistributorEmployee{}

// DistributorEmployee struct for DistributorEmployee
type DistributorEmployee struct {
	Data DistributorEmployeeData `json:"data"`
}

type _DistributorEmployee DistributorEmployee

// NewDistributorEmployee instantiates a new DistributorEmployee object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDistributorEmployee(data DistributorEmployeeData) *DistributorEmployee {
	this := DistributorEmployee{}
	this.Data = data
	return &this
}

// NewDistributorEmployeeWithDefaults instantiates a new DistributorEmployee object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDistributorEmployeeWithDefaults() *DistributorEmployee {
	this := DistributorEmployee{}
	return &this
}

// GetData returns the Data field value
func (o *DistributorEmployee) GetData() DistributorEmployeeData {
	if o == nil {
		var ret DistributorEmployeeData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DistributorEmployee) GetDataOk() (*DistributorEmployeeData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DistributorEmployee) SetData(v DistributorEmployeeData) {
	o.Data = v
}

func (o DistributorEmployee) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DistributorEmployee) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DistributorEmployee) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDistributorEmployee := _DistributorEmployee{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDistributorEmployee)

	if err != nil {
		return err
	}

	*o = DistributorEmployee(varDistributorEmployee)

	return err
}

type NullableDistributorEmployee struct {
	value *DistributorEmployee
	isSet bool
}

func (v NullableDistributorEmployee) Get() *DistributorEmployee {
	return v.value
}

func (v *NullableDistributorEmployee) Set(val *DistributorEmployee) {
	v.value = val
	v.isSet = true
}

func (v NullableDistributorEmployee) IsSet() bool {
	return v.isSet
}

func (v *NullableDistributorEmployee) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDistributorEmployee(val *DistributorEmployee) *NullableDistributorEmployee {
	return &NullableDistributorEmployee{value: val, isSet: true}
}

func (v NullableDistributorEmployee) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDistributorEmployee) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


