/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PlaceEmployeeUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlaceEmployeeUpdate{}

// PlaceEmployeeUpdate struct for PlaceEmployeeUpdate
type PlaceEmployeeUpdate struct {
	Data PlaceEmployeeUpdateData `json:"data"`
}

type _PlaceEmployeeUpdate PlaceEmployeeUpdate

// NewPlaceEmployeeUpdate instantiates a new PlaceEmployeeUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlaceEmployeeUpdate(data PlaceEmployeeUpdateData) *PlaceEmployeeUpdate {
	this := PlaceEmployeeUpdate{}
	this.Data = data
	return &this
}

// NewPlaceEmployeeUpdateWithDefaults instantiates a new PlaceEmployeeUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlaceEmployeeUpdateWithDefaults() *PlaceEmployeeUpdate {
	this := PlaceEmployeeUpdate{}
	return &this
}

// GetData returns the Data field value
func (o *PlaceEmployeeUpdate) GetData() PlaceEmployeeUpdateData {
	if o == nil {
		var ret PlaceEmployeeUpdateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PlaceEmployeeUpdate) GetDataOk() (*PlaceEmployeeUpdateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *PlaceEmployeeUpdate) SetData(v PlaceEmployeeUpdateData) {
	o.Data = v
}

func (o PlaceEmployeeUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlaceEmployeeUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *PlaceEmployeeUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlaceEmployeeUpdate := _PlaceEmployeeUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPlaceEmployeeUpdate)

	if err != nil {
		return err
	}

	*o = PlaceEmployeeUpdate(varPlaceEmployeeUpdate)

	return err
}

type NullablePlaceEmployeeUpdate struct {
	value *PlaceEmployeeUpdate
	isSet bool
}

func (v NullablePlaceEmployeeUpdate) Get() *PlaceEmployeeUpdate {
	return v.value
}

func (v *NullablePlaceEmployeeUpdate) Set(val *PlaceEmployeeUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullablePlaceEmployeeUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullablePlaceEmployeeUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlaceEmployeeUpdate(val *PlaceEmployeeUpdate) *NullablePlaceEmployeeUpdate {
	return &NullablePlaceEmployeeUpdate{value: val, isSet: true}
}

func (v NullablePlaceEmployeeUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlaceEmployeeUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


