/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DistributorDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DistributorDataAttributes{}

// DistributorDataAttributes struct for DistributorDataAttributes
type DistributorDataAttributes struct {
	// Distributor name
	Name string `json:"name"`
	// Owner ID
	OwnerId string `json:"owner_id"`
}

type _DistributorDataAttributes DistributorDataAttributes

// NewDistributorDataAttributes instantiates a new DistributorDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDistributorDataAttributes(name string, ownerId string) *DistributorDataAttributes {
	this := DistributorDataAttributes{}
	this.Name = name
	this.OwnerId = ownerId
	return &this
}

// NewDistributorDataAttributesWithDefaults instantiates a new DistributorDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDistributorDataAttributesWithDefaults() *DistributorDataAttributes {
	this := DistributorDataAttributes{}
	return &this
}

// GetName returns the Name field value
func (o *DistributorDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DistributorDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DistributorDataAttributes) SetName(v string) {
	o.Name = v
}

// GetOwnerId returns the OwnerId field value
func (o *DistributorDataAttributes) GetOwnerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OwnerId
}

// GetOwnerIdOk returns a tuple with the OwnerId field value
// and a boolean to check if the value has been set.
func (o *DistributorDataAttributes) GetOwnerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OwnerId, true
}

// SetOwnerId sets field value
func (o *DistributorDataAttributes) SetOwnerId(v string) {
	o.OwnerId = v
}

func (o DistributorDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DistributorDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["owner_id"] = o.OwnerId
	return toSerialize, nil
}

func (o *DistributorDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"owner_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDistributorDataAttributes := _DistributorDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDistributorDataAttributes)

	if err != nil {
		return err
	}

	*o = DistributorDataAttributes(varDistributorDataAttributes)

	return err
}

type NullableDistributorDataAttributes struct {
	value *DistributorDataAttributes
	isSet bool
}

func (v NullableDistributorDataAttributes) Get() *DistributorDataAttributes {
	return v.value
}

func (v *NullableDistributorDataAttributes) Set(val *DistributorDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableDistributorDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableDistributorDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDistributorDataAttributes(val *DistributorDataAttributes) *NullableDistributorDataAttributes {
	return &NullableDistributorDataAttributes{value: val, isSet: true}
}

func (v NullableDistributorDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDistributorDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


