/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PlaceEmployee type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlaceEmployee{}

// PlaceEmployee struct for PlaceEmployee
type PlaceEmployee struct {
	Data PlaceEmployeeData `json:"data"`
}

type _PlaceEmployee PlaceEmployee

// NewPlaceEmployee instantiates a new PlaceEmployee object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlaceEmployee(data PlaceEmployeeData) *PlaceEmployee {
	this := PlaceEmployee{}
	this.Data = data
	return &this
}

// NewPlaceEmployeeWithDefaults instantiates a new PlaceEmployee object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlaceEmployeeWithDefaults() *PlaceEmployee {
	this := PlaceEmployee{}
	return &this
}

// GetData returns the Data field value
func (o *PlaceEmployee) GetData() PlaceEmployeeData {
	if o == nil {
		var ret PlaceEmployeeData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PlaceEmployee) GetDataOk() (*PlaceEmployeeData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *PlaceEmployee) SetData(v PlaceEmployeeData) {
	o.Data = v
}

func (o PlaceEmployee) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlaceEmployee) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *PlaceEmployee) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlaceEmployee := _PlaceEmployee{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPlaceEmployee)

	if err != nil {
		return err
	}

	*o = PlaceEmployee(varPlaceEmployee)

	return err
}

type NullablePlaceEmployee struct {
	value *PlaceEmployee
	isSet bool
}

func (v NullablePlaceEmployee) Get() *PlaceEmployee {
	return v.value
}

func (v *NullablePlaceEmployee) Set(val *PlaceEmployee) {
	v.value = val
	v.isSet = true
}

func (v NullablePlaceEmployee) IsSet() bool {
	return v.isSet
}

func (v *NullablePlaceEmployee) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlaceEmployee(val *PlaceEmployee) *NullablePlaceEmployee {
	return &NullablePlaceEmployee{value: val, isSet: true}
}

func (v NullablePlaceEmployee) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlaceEmployee) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


