/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DistributorUpdateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DistributorUpdateData{}

// DistributorUpdateData struct for DistributorUpdateData
type DistributorUpdateData struct {
	// Resource ID
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes DistributorUpdateDataAttributes `json:"attributes"`
}

type _DistributorUpdateData DistributorUpdateData

// NewDistributorUpdateData instantiates a new DistributorUpdateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDistributorUpdateData(id string, type_ string, attributes DistributorUpdateDataAttributes) *DistributorUpdateData {
	this := DistributorUpdateData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewDistributorUpdateDataWithDefaults instantiates a new DistributorUpdateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDistributorUpdateDataWithDefaults() *DistributorUpdateData {
	this := DistributorUpdateData{}
	return &this
}

// GetId returns the Id field value
func (o *DistributorUpdateData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DistributorUpdateData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DistributorUpdateData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *DistributorUpdateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *DistributorUpdateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *DistributorUpdateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *DistributorUpdateData) GetAttributes() DistributorUpdateDataAttributes {
	if o == nil {
		var ret DistributorUpdateDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *DistributorUpdateData) GetAttributesOk() (*DistributorUpdateDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *DistributorUpdateData) SetAttributes(v DistributorUpdateDataAttributes) {
	o.Attributes = v
}

func (o DistributorUpdateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DistributorUpdateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *DistributorUpdateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDistributorUpdateData := _DistributorUpdateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDistributorUpdateData)

	if err != nil {
		return err
	}

	*o = DistributorUpdateData(varDistributorUpdateData)

	return err
}

type NullableDistributorUpdateData struct {
	value *DistributorUpdateData
	isSet bool
}

func (v NullableDistributorUpdateData) Get() *DistributorUpdateData {
	return v.value
}

func (v *NullableDistributorUpdateData) Set(val *DistributorUpdateData) {
	v.value = val
	v.isSet = true
}

func (v NullableDistributorUpdateData) IsSet() bool {
	return v.isSet
}

func (v *NullableDistributorUpdateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDistributorUpdateData(val *DistributorUpdateData) *NullableDistributorUpdateData {
	return &NullableDistributorUpdateData{value: val, isSet: true}
}

func (v NullableDistributorUpdateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDistributorUpdateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


