/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DistributorEmployeeDeleteDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DistributorEmployeeDeleteDataAttributes{}

// DistributorEmployeeDeleteDataAttributes struct for DistributorEmployeeDeleteDataAttributes
type DistributorEmployeeDeleteDataAttributes struct {
	// User ID
	UserId string `json:"user_id"`
}

type _DistributorEmployeeDeleteDataAttributes DistributorEmployeeDeleteDataAttributes

// NewDistributorEmployeeDeleteDataAttributes instantiates a new DistributorEmployeeDeleteDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDistributorEmployeeDeleteDataAttributes(userId string) *DistributorEmployeeDeleteDataAttributes {
	this := DistributorEmployeeDeleteDataAttributes{}
	this.UserId = userId
	return &this
}

// NewDistributorEmployeeDeleteDataAttributesWithDefaults instantiates a new DistributorEmployeeDeleteDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDistributorEmployeeDeleteDataAttributesWithDefaults() *DistributorEmployeeDeleteDataAttributes {
	this := DistributorEmployeeDeleteDataAttributes{}
	return &this
}

// GetUserId returns the UserId field value
func (o *DistributorEmployeeDeleteDataAttributes) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *DistributorEmployeeDeleteDataAttributes) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *DistributorEmployeeDeleteDataAttributes) SetUserId(v string) {
	o.UserId = v
}

func (o DistributorEmployeeDeleteDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DistributorEmployeeDeleteDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user_id"] = o.UserId
	return toSerialize, nil
}

func (o *DistributorEmployeeDeleteDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDistributorEmployeeDeleteDataAttributes := _DistributorEmployeeDeleteDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDistributorEmployeeDeleteDataAttributes)

	if err != nil {
		return err
	}

	*o = DistributorEmployeeDeleteDataAttributes(varDistributorEmployeeDeleteDataAttributes)

	return err
}

type NullableDistributorEmployeeDeleteDataAttributes struct {
	value *DistributorEmployeeDeleteDataAttributes
	isSet bool
}

func (v NullableDistributorEmployeeDeleteDataAttributes) Get() *DistributorEmployeeDeleteDataAttributes {
	return v.value
}

func (v *NullableDistributorEmployeeDeleteDataAttributes) Set(val *DistributorEmployeeDeleteDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableDistributorEmployeeDeleteDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableDistributorEmployeeDeleteDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDistributorEmployeeDeleteDataAttributes(val *DistributorEmployeeDeleteDataAttributes) *NullableDistributorEmployeeDeleteDataAttributes {
	return &NullableDistributorEmployeeDeleteDataAttributes{value: val, isSet: true}
}

func (v NullableDistributorEmployeeDeleteDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDistributorEmployeeDeleteDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


