/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DistributorUpdateDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DistributorUpdateDataAttributes{}

// DistributorUpdateDataAttributes struct for DistributorUpdateDataAttributes
type DistributorUpdateDataAttributes struct {
	// Distributor name
	Name string `json:"name"`
}

type _DistributorUpdateDataAttributes DistributorUpdateDataAttributes

// NewDistributorUpdateDataAttributes instantiates a new DistributorUpdateDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDistributorUpdateDataAttributes(name string) *DistributorUpdateDataAttributes {
	this := DistributorUpdateDataAttributes{}
	this.Name = name
	return &this
}

// NewDistributorUpdateDataAttributesWithDefaults instantiates a new DistributorUpdateDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDistributorUpdateDataAttributesWithDefaults() *DistributorUpdateDataAttributes {
	this := DistributorUpdateDataAttributes{}
	return &this
}

// GetName returns the Name field value
func (o *DistributorUpdateDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DistributorUpdateDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DistributorUpdateDataAttributes) SetName(v string) {
	o.Name = v
}

func (o DistributorUpdateDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DistributorUpdateDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *DistributorUpdateDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDistributorUpdateDataAttributes := _DistributorUpdateDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDistributorUpdateDataAttributes)

	if err != nil {
		return err
	}

	*o = DistributorUpdateDataAttributes(varDistributorUpdateDataAttributes)

	return err
}

type NullableDistributorUpdateDataAttributes struct {
	value *DistributorUpdateDataAttributes
	isSet bool
}

func (v NullableDistributorUpdateDataAttributes) Get() *DistributorUpdateDataAttributes {
	return v.value
}

func (v *NullableDistributorUpdateDataAttributes) Set(val *DistributorUpdateDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableDistributorUpdateDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableDistributorUpdateDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDistributorUpdateDataAttributes(val *DistributorUpdateDataAttributes) *NullableDistributorUpdateDataAttributes {
	return &NullableDistributorUpdateDataAttributes{value: val, isSet: true}
}

func (v NullableDistributorUpdateDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDistributorUpdateDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


