/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DistributorCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DistributorCreate{}

// DistributorCreate struct for DistributorCreate
type DistributorCreate struct {
	Data DistributorCreateData `json:"data"`
}

type _DistributorCreate DistributorCreate

// NewDistributorCreate instantiates a new DistributorCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDistributorCreate(data DistributorCreateData) *DistributorCreate {
	this := DistributorCreate{}
	this.Data = data
	return &this
}

// NewDistributorCreateWithDefaults instantiates a new DistributorCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDistributorCreateWithDefaults() *DistributorCreate {
	this := DistributorCreate{}
	return &this
}

// GetData returns the Data field value
func (o *DistributorCreate) GetData() DistributorCreateData {
	if o == nil {
		var ret DistributorCreateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DistributorCreate) GetDataOk() (*DistributorCreateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DistributorCreate) SetData(v DistributorCreateData) {
	o.Data = v
}

func (o DistributorCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DistributorCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DistributorCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDistributorCreate := _DistributorCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDistributorCreate)

	if err != nil {
		return err
	}

	*o = DistributorCreate(varDistributorCreate)

	return err
}

type NullableDistributorCreate struct {
	value *DistributorCreate
	isSet bool
}

func (v NullableDistributorCreate) Get() *DistributorCreate {
	return v.value
}

func (v *NullableDistributorCreate) Set(val *DistributorCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableDistributorCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableDistributorCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDistributorCreate(val *DistributorCreate) *NullableDistributorCreate {
	return &NullableDistributorCreate{value: val, isSet: true}
}

func (v NullableDistributorCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDistributorCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


