/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DistributorEmployeeDelete type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DistributorEmployeeDelete{}

// DistributorEmployeeDelete struct for DistributorEmployeeDelete
type DistributorEmployeeDelete struct {
	Data DistributorEmployeeDeleteData `json:"data"`
}

type _DistributorEmployeeDelete DistributorEmployeeDelete

// NewDistributorEmployeeDelete instantiates a new DistributorEmployeeDelete object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDistributorEmployeeDelete(data DistributorEmployeeDeleteData) *DistributorEmployeeDelete {
	this := DistributorEmployeeDelete{}
	this.Data = data
	return &this
}

// NewDistributorEmployeeDeleteWithDefaults instantiates a new DistributorEmployeeDelete object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDistributorEmployeeDeleteWithDefaults() *DistributorEmployeeDelete {
	this := DistributorEmployeeDelete{}
	return &this
}

// GetData returns the Data field value
func (o *DistributorEmployeeDelete) GetData() DistributorEmployeeDeleteData {
	if o == nil {
		var ret DistributorEmployeeDeleteData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DistributorEmployeeDelete) GetDataOk() (*DistributorEmployeeDeleteData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DistributorEmployeeDelete) SetData(v DistributorEmployeeDeleteData) {
	o.Data = v
}

func (o DistributorEmployeeDelete) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DistributorEmployeeDelete) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DistributorEmployeeDelete) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDistributorEmployeeDelete := _DistributorEmployeeDelete{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDistributorEmployeeDelete)

	if err != nil {
		return err
	}

	*o = DistributorEmployeeDelete(varDistributorEmployeeDelete)

	return err
}

type NullableDistributorEmployeeDelete struct {
	value *DistributorEmployeeDelete
	isSet bool
}

func (v NullableDistributorEmployeeDelete) Get() *DistributorEmployeeDelete {
	return v.value
}

func (v *NullableDistributorEmployeeDelete) Set(val *DistributorEmployeeDelete) {
	v.value = val
	v.isSet = true
}

func (v NullableDistributorEmployeeDelete) IsSet() bool {
	return v.isSet
}

func (v *NullableDistributorEmployeeDelete) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDistributorEmployeeDelete(val *DistributorEmployeeDelete) *NullableDistributorEmployeeDelete {
	return &NullableDistributorEmployeeDelete{value: val, isSet: true}
}

func (v NullableDistributorEmployeeDelete) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDistributorEmployeeDelete) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


