/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DistributorEmployeeUpdateDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DistributorEmployeeUpdateDataAttributes{}

// DistributorEmployeeUpdateDataAttributes struct for DistributorEmployeeUpdateDataAttributes
type DistributorEmployeeUpdateDataAttributes struct {
	// User role
	Role string `json:"role"`
}

type _DistributorEmployeeUpdateDataAttributes DistributorEmployeeUpdateDataAttributes

// NewDistributorEmployeeUpdateDataAttributes instantiates a new DistributorEmployeeUpdateDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDistributorEmployeeUpdateDataAttributes(role string) *DistributorEmployeeUpdateDataAttributes {
	this := DistributorEmployeeUpdateDataAttributes{}
	this.Role = role
	return &this
}

// NewDistributorEmployeeUpdateDataAttributesWithDefaults instantiates a new DistributorEmployeeUpdateDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDistributorEmployeeUpdateDataAttributesWithDefaults() *DistributorEmployeeUpdateDataAttributes {
	this := DistributorEmployeeUpdateDataAttributes{}
	return &this
}

// GetRole returns the Role field value
func (o *DistributorEmployeeUpdateDataAttributes) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *DistributorEmployeeUpdateDataAttributes) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *DistributorEmployeeUpdateDataAttributes) SetRole(v string) {
	o.Role = v
}

func (o DistributorEmployeeUpdateDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DistributorEmployeeUpdateDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["role"] = o.Role
	return toSerialize, nil
}

func (o *DistributorEmployeeUpdateDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDistributorEmployeeUpdateDataAttributes := _DistributorEmployeeUpdateDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDistributorEmployeeUpdateDataAttributes)

	if err != nil {
		return err
	}

	*o = DistributorEmployeeUpdateDataAttributes(varDistributorEmployeeUpdateDataAttributes)

	return err
}

type NullableDistributorEmployeeUpdateDataAttributes struct {
	value *DistributorEmployeeUpdateDataAttributes
	isSet bool
}

func (v NullableDistributorEmployeeUpdateDataAttributes) Get() *DistributorEmployeeUpdateDataAttributes {
	return v.value
}

func (v *NullableDistributorEmployeeUpdateDataAttributes) Set(val *DistributorEmployeeUpdateDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableDistributorEmployeeUpdateDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableDistributorEmployeeUpdateDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDistributorEmployeeUpdateDataAttributes(val *DistributorEmployeeUpdateDataAttributes) *NullableDistributorEmployeeUpdateDataAttributes {
	return &NullableDistributorEmployeeUpdateDataAttributes{value: val, isSet: true}
}

func (v NullableDistributorEmployeeUpdateDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDistributorEmployeeUpdateDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


