/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmployeeDeleteDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmployeeDeleteDataAttributes{}

// EmployeeDeleteDataAttributes struct for EmployeeDeleteDataAttributes
type EmployeeDeleteDataAttributes struct {
	// User ID
	UserId string `json:"user_id"`
}

type _EmployeeDeleteDataAttributes EmployeeDeleteDataAttributes

// NewEmployeeDeleteDataAttributes instantiates a new EmployeeDeleteDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmployeeDeleteDataAttributes(userId string) *EmployeeDeleteDataAttributes {
	this := EmployeeDeleteDataAttributes{}
	this.UserId = userId
	return &this
}

// NewEmployeeDeleteDataAttributesWithDefaults instantiates a new EmployeeDeleteDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmployeeDeleteDataAttributesWithDefaults() *EmployeeDeleteDataAttributes {
	this := EmployeeDeleteDataAttributes{}
	return &this
}

// GetUserId returns the UserId field value
func (o *EmployeeDeleteDataAttributes) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *EmployeeDeleteDataAttributes) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *EmployeeDeleteDataAttributes) SetUserId(v string) {
	o.UserId = v
}

func (o EmployeeDeleteDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmployeeDeleteDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user_id"] = o.UserId
	return toSerialize, nil
}

func (o *EmployeeDeleteDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmployeeDeleteDataAttributes := _EmployeeDeleteDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmployeeDeleteDataAttributes)

	if err != nil {
		return err
	}

	*o = EmployeeDeleteDataAttributes(varEmployeeDeleteDataAttributes)

	return err
}

type NullableEmployeeDeleteDataAttributes struct {
	value *EmployeeDeleteDataAttributes
	isSet bool
}

func (v NullableEmployeeDeleteDataAttributes) Get() *EmployeeDeleteDataAttributes {
	return v.value
}

func (v *NullableEmployeeDeleteDataAttributes) Set(val *EmployeeDeleteDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableEmployeeDeleteDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableEmployeeDeleteDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmployeeDeleteDataAttributes(val *EmployeeDeleteDataAttributes) *NullableEmployeeDeleteDataAttributes {
	return &NullableEmployeeDeleteDataAttributes{value: val, isSet: true}
}

func (v NullableEmployeeDeleteDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmployeeDeleteDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


