/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PlaceEmployeeCreateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlaceEmployeeCreateData{}

// PlaceEmployeeCreateData struct for PlaceEmployeeCreateData
type PlaceEmployeeCreateData struct {
	Type string `json:"type"`
	Attributes PlaceEmployeeCreateDataAttributes `json:"attributes"`
}

type _PlaceEmployeeCreateData PlaceEmployeeCreateData

// NewPlaceEmployeeCreateData instantiates a new PlaceEmployeeCreateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlaceEmployeeCreateData(type_ string, attributes PlaceEmployeeCreateDataAttributes) *PlaceEmployeeCreateData {
	this := PlaceEmployeeCreateData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewPlaceEmployeeCreateDataWithDefaults instantiates a new PlaceEmployeeCreateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlaceEmployeeCreateDataWithDefaults() *PlaceEmployeeCreateData {
	this := PlaceEmployeeCreateData{}
	return &this
}

// GetType returns the Type field value
func (o *PlaceEmployeeCreateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PlaceEmployeeCreateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PlaceEmployeeCreateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *PlaceEmployeeCreateData) GetAttributes() PlaceEmployeeCreateDataAttributes {
	if o == nil {
		var ret PlaceEmployeeCreateDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *PlaceEmployeeCreateData) GetAttributesOk() (*PlaceEmployeeCreateDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *PlaceEmployeeCreateData) SetAttributes(v PlaceEmployeeCreateDataAttributes) {
	o.Attributes = v
}

func (o PlaceEmployeeCreateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlaceEmployeeCreateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *PlaceEmployeeCreateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlaceEmployeeCreateData := _PlaceEmployeeCreateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPlaceEmployeeCreateData)

	if err != nil {
		return err
	}

	*o = PlaceEmployeeCreateData(varPlaceEmployeeCreateData)

	return err
}

type NullablePlaceEmployeeCreateData struct {
	value *PlaceEmployeeCreateData
	isSet bool
}

func (v NullablePlaceEmployeeCreateData) Get() *PlaceEmployeeCreateData {
	return v.value
}

func (v *NullablePlaceEmployeeCreateData) Set(val *PlaceEmployeeCreateData) {
	v.value = val
	v.isSet = true
}

func (v NullablePlaceEmployeeCreateData) IsSet() bool {
	return v.isSet
}

func (v *NullablePlaceEmployeeCreateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlaceEmployeeCreateData(val *PlaceEmployeeCreateData) *NullablePlaceEmployeeCreateData {
	return &NullablePlaceEmployeeCreateData{value: val, isSet: true}
}

func (v NullablePlaceEmployeeCreateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlaceEmployeeCreateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


