/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmployeeDeleteData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmployeeDeleteData{}

// EmployeeDeleteData struct for EmployeeDeleteData
type EmployeeDeleteData struct {
	Type string `json:"type"`
	Attributes EmployeeDeleteDataAttributes `json:"attributes"`
}

type _EmployeeDeleteData EmployeeDeleteData

// NewEmployeeDeleteData instantiates a new EmployeeDeleteData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmployeeDeleteData(type_ string, attributes EmployeeDeleteDataAttributes) *EmployeeDeleteData {
	this := EmployeeDeleteData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewEmployeeDeleteDataWithDefaults instantiates a new EmployeeDeleteData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmployeeDeleteDataWithDefaults() *EmployeeDeleteData {
	this := EmployeeDeleteData{}
	return &this
}

// GetType returns the Type field value
func (o *EmployeeDeleteData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *EmployeeDeleteData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *EmployeeDeleteData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *EmployeeDeleteData) GetAttributes() EmployeeDeleteDataAttributes {
	if o == nil {
		var ret EmployeeDeleteDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *EmployeeDeleteData) GetAttributesOk() (*EmployeeDeleteDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *EmployeeDeleteData) SetAttributes(v EmployeeDeleteDataAttributes) {
	o.Attributes = v
}

func (o EmployeeDeleteData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmployeeDeleteData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *EmployeeDeleteData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmployeeDeleteData := _EmployeeDeleteData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmployeeDeleteData)

	if err != nil {
		return err
	}

	*o = EmployeeDeleteData(varEmployeeDeleteData)

	return err
}

type NullableEmployeeDeleteData struct {
	value *EmployeeDeleteData
	isSet bool
}

func (v NullableEmployeeDeleteData) Get() *EmployeeDeleteData {
	return v.value
}

func (v *NullableEmployeeDeleteData) Set(val *EmployeeDeleteData) {
	v.value = val
	v.isSet = true
}

func (v NullableEmployeeDeleteData) IsSet() bool {
	return v.isSet
}

func (v *NullableEmployeeDeleteData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmployeeDeleteData(val *EmployeeDeleteData) *NullableEmployeeDeleteData {
	return &NullableEmployeeDeleteData{value: val, isSet: true}
}

func (v NullableEmployeeDeleteData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmployeeDeleteData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


