/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DistributorEmployeeCollectionDataAttributesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DistributorEmployeeCollectionDataAttributesInner{}

// DistributorEmployeeCollectionDataAttributesInner struct for DistributorEmployeeCollectionDataAttributesInner
type DistributorEmployeeCollectionDataAttributesInner struct {
	Data DistributorEmployeeData `json:"data"`
}

type _DistributorEmployeeCollectionDataAttributesInner DistributorEmployeeCollectionDataAttributesInner

// NewDistributorEmployeeCollectionDataAttributesInner instantiates a new DistributorEmployeeCollectionDataAttributesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDistributorEmployeeCollectionDataAttributesInner(data DistributorEmployeeData) *DistributorEmployeeCollectionDataAttributesInner {
	this := DistributorEmployeeCollectionDataAttributesInner{}
	this.Data = data
	return &this
}

// NewDistributorEmployeeCollectionDataAttributesInnerWithDefaults instantiates a new DistributorEmployeeCollectionDataAttributesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDistributorEmployeeCollectionDataAttributesInnerWithDefaults() *DistributorEmployeeCollectionDataAttributesInner {
	this := DistributorEmployeeCollectionDataAttributesInner{}
	return &this
}

// GetData returns the Data field value
func (o *DistributorEmployeeCollectionDataAttributesInner) GetData() DistributorEmployeeData {
	if o == nil {
		var ret DistributorEmployeeData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DistributorEmployeeCollectionDataAttributesInner) GetDataOk() (*DistributorEmployeeData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DistributorEmployeeCollectionDataAttributesInner) SetData(v DistributorEmployeeData) {
	o.Data = v
}

func (o DistributorEmployeeCollectionDataAttributesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DistributorEmployeeCollectionDataAttributesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DistributorEmployeeCollectionDataAttributesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDistributorEmployeeCollectionDataAttributesInner := _DistributorEmployeeCollectionDataAttributesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDistributorEmployeeCollectionDataAttributesInner)

	if err != nil {
		return err
	}

	*o = DistributorEmployeeCollectionDataAttributesInner(varDistributorEmployeeCollectionDataAttributesInner)

	return err
}

type NullableDistributorEmployeeCollectionDataAttributesInner struct {
	value *DistributorEmployeeCollectionDataAttributesInner
	isSet bool
}

func (v NullableDistributorEmployeeCollectionDataAttributesInner) Get() *DistributorEmployeeCollectionDataAttributesInner {
	return v.value
}

func (v *NullableDistributorEmployeeCollectionDataAttributesInner) Set(val *DistributorEmployeeCollectionDataAttributesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableDistributorEmployeeCollectionDataAttributesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableDistributorEmployeeCollectionDataAttributesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDistributorEmployeeCollectionDataAttributesInner(val *DistributorEmployeeCollectionDataAttributesInner) *NullableDistributorEmployeeCollectionDataAttributesInner {
	return &NullableDistributorEmployeeCollectionDataAttributesInner{value: val, isSet: true}
}

func (v NullableDistributorEmployeeCollectionDataAttributesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDistributorEmployeeCollectionDataAttributesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


