/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DistributorCreateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DistributorCreateData{}

// DistributorCreateData struct for DistributorCreateData
type DistributorCreateData struct {
	// Resource ID
	Id *string `json:"id,omitempty"`
	Type string `json:"type"`
	Attributes DistributorUpdateDataAttributes `json:"attributes"`
}

type _DistributorCreateData DistributorCreateData

// NewDistributorCreateData instantiates a new DistributorCreateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDistributorCreateData(type_ string, attributes DistributorUpdateDataAttributes) *DistributorCreateData {
	this := DistributorCreateData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewDistributorCreateDataWithDefaults instantiates a new DistributorCreateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDistributorCreateDataWithDefaults() *DistributorCreateData {
	this := DistributorCreateData{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DistributorCreateData) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DistributorCreateData) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DistributorCreateData) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DistributorCreateData) SetId(v string) {
	o.Id = &v
}

// GetType returns the Type field value
func (o *DistributorCreateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *DistributorCreateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *DistributorCreateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *DistributorCreateData) GetAttributes() DistributorUpdateDataAttributes {
	if o == nil {
		var ret DistributorUpdateDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *DistributorCreateData) GetAttributesOk() (*DistributorUpdateDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *DistributorCreateData) SetAttributes(v DistributorUpdateDataAttributes) {
	o.Attributes = v
}

func (o DistributorCreateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DistributorCreateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *DistributorCreateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDistributorCreateData := _DistributorCreateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDistributorCreateData)

	if err != nil {
		return err
	}

	*o = DistributorCreateData(varDistributorCreateData)

	return err
}

type NullableDistributorCreateData struct {
	value *DistributorCreateData
	isSet bool
}

func (v NullableDistributorCreateData) Get() *DistributorCreateData {
	return v.value
}

func (v *NullableDistributorCreateData) Set(val *DistributorCreateData) {
	v.value = val
	v.isSet = true
}

func (v NullableDistributorCreateData) IsSet() bool {
	return v.isSet
}

func (v *NullableDistributorCreateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDistributorCreateData(val *DistributorCreateData) *NullableDistributorCreateData {
	return &NullableDistributorCreateData{value: val, isSet: true}
}

func (v NullableDistributorCreateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDistributorCreateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


