/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmployeeCollectionDataAttributesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmployeeCollectionDataAttributesInner{}

// EmployeeCollectionDataAttributesInner struct for EmployeeCollectionDataAttributesInner
type EmployeeCollectionDataAttributesInner struct {
	Data EmployeeData `json:"data"`
}

type _EmployeeCollectionDataAttributesInner EmployeeCollectionDataAttributesInner

// NewEmployeeCollectionDataAttributesInner instantiates a new EmployeeCollectionDataAttributesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmployeeCollectionDataAttributesInner(data EmployeeData) *EmployeeCollectionDataAttributesInner {
	this := EmployeeCollectionDataAttributesInner{}
	this.Data = data
	return &this
}

// NewEmployeeCollectionDataAttributesInnerWithDefaults instantiates a new EmployeeCollectionDataAttributesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmployeeCollectionDataAttributesInnerWithDefaults() *EmployeeCollectionDataAttributesInner {
	this := EmployeeCollectionDataAttributesInner{}
	return &this
}

// GetData returns the Data field value
func (o *EmployeeCollectionDataAttributesInner) GetData() EmployeeData {
	if o == nil {
		var ret EmployeeData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *EmployeeCollectionDataAttributesInner) GetDataOk() (*EmployeeData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *EmployeeCollectionDataAttributesInner) SetData(v EmployeeData) {
	o.Data = v
}

func (o EmployeeCollectionDataAttributesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmployeeCollectionDataAttributesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *EmployeeCollectionDataAttributesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmployeeCollectionDataAttributesInner := _EmployeeCollectionDataAttributesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmployeeCollectionDataAttributesInner)

	if err != nil {
		return err
	}

	*o = EmployeeCollectionDataAttributesInner(varEmployeeCollectionDataAttributesInner)

	return err
}

type NullableEmployeeCollectionDataAttributesInner struct {
	value *EmployeeCollectionDataAttributesInner
	isSet bool
}

func (v NullableEmployeeCollectionDataAttributesInner) Get() *EmployeeCollectionDataAttributesInner {
	return v.value
}

func (v *NullableEmployeeCollectionDataAttributesInner) Set(val *EmployeeCollectionDataAttributesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableEmployeeCollectionDataAttributesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableEmployeeCollectionDataAttributesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmployeeCollectionDataAttributesInner(val *EmployeeCollectionDataAttributesInner) *NullableEmployeeCollectionDataAttributesInner {
	return &NullableEmployeeCollectionDataAttributesInner{value: val, isSet: true}
}

func (v NullableEmployeeCollectionDataAttributesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmployeeCollectionDataAttributesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


