/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DistributorUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DistributorUpdate{}

// DistributorUpdate struct for DistributorUpdate
type DistributorUpdate struct {
	Data DistributorUpdateData `json:"data"`
}

type _DistributorUpdate DistributorUpdate

// NewDistributorUpdate instantiates a new DistributorUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDistributorUpdate(data DistributorUpdateData) *DistributorUpdate {
	this := DistributorUpdate{}
	this.Data = data
	return &this
}

// NewDistributorUpdateWithDefaults instantiates a new DistributorUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDistributorUpdateWithDefaults() *DistributorUpdate {
	this := DistributorUpdate{}
	return &this
}

// GetData returns the Data field value
func (o *DistributorUpdate) GetData() DistributorUpdateData {
	if o == nil {
		var ret DistributorUpdateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DistributorUpdate) GetDataOk() (*DistributorUpdateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DistributorUpdate) SetData(v DistributorUpdateData) {
	o.Data = v
}

func (o DistributorUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DistributorUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DistributorUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDistributorUpdate := _DistributorUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDistributorUpdate)

	if err != nil {
		return err
	}

	*o = DistributorUpdate(varDistributorUpdate)

	return err
}

type NullableDistributorUpdate struct {
	value *DistributorUpdate
	isSet bool
}

func (v NullableDistributorUpdate) Get() *DistributorUpdate {
	return v.value
}

func (v *NullableDistributorUpdate) Set(val *DistributorUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableDistributorUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableDistributorUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDistributorUpdate(val *DistributorUpdate) *NullableDistributorUpdate {
	return &NullableDistributorUpdate{value: val, isSet: true}
}

func (v NullableDistributorUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDistributorUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


