/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DistributorEmployeeCreateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DistributorEmployeeCreateData{}

// DistributorEmployeeCreateData struct for DistributorEmployeeCreateData
type DistributorEmployeeCreateData struct {
	Type string `json:"type"`
	Attributes DistributorEmployeeCreateDataAttributes `json:"attributes"`
}

type _DistributorEmployeeCreateData DistributorEmployeeCreateData

// NewDistributorEmployeeCreateData instantiates a new DistributorEmployeeCreateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDistributorEmployeeCreateData(type_ string, attributes DistributorEmployeeCreateDataAttributes) *DistributorEmployeeCreateData {
	this := DistributorEmployeeCreateData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewDistributorEmployeeCreateDataWithDefaults instantiates a new DistributorEmployeeCreateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDistributorEmployeeCreateDataWithDefaults() *DistributorEmployeeCreateData {
	this := DistributorEmployeeCreateData{}
	return &this
}

// GetType returns the Type field value
func (o *DistributorEmployeeCreateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *DistributorEmployeeCreateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *DistributorEmployeeCreateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *DistributorEmployeeCreateData) GetAttributes() DistributorEmployeeCreateDataAttributes {
	if o == nil {
		var ret DistributorEmployeeCreateDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *DistributorEmployeeCreateData) GetAttributesOk() (*DistributorEmployeeCreateDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *DistributorEmployeeCreateData) SetAttributes(v DistributorEmployeeCreateDataAttributes) {
	o.Attributes = v
}

func (o DistributorEmployeeCreateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DistributorEmployeeCreateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *DistributorEmployeeCreateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDistributorEmployeeCreateData := _DistributorEmployeeCreateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDistributorEmployeeCreateData)

	if err != nil {
		return err
	}

	*o = DistributorEmployeeCreateData(varDistributorEmployeeCreateData)

	return err
}

type NullableDistributorEmployeeCreateData struct {
	value *DistributorEmployeeCreateData
	isSet bool
}

func (v NullableDistributorEmployeeCreateData) Get() *DistributorEmployeeCreateData {
	return v.value
}

func (v *NullableDistributorEmployeeCreateData) Set(val *DistributorEmployeeCreateData) {
	v.value = val
	v.isSet = true
}

func (v NullableDistributorEmployeeCreateData) IsSet() bool {
	return v.isSet
}

func (v *NullableDistributorEmployeeCreateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDistributorEmployeeCreateData(val *DistributorEmployeeCreateData) *NullableDistributorEmployeeCreateData {
	return &NullableDistributorEmployeeCreateData{value: val, isSet: true}
}

func (v NullableDistributorEmployeeCreateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDistributorEmployeeCreateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


