/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmployeeUpdateDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmployeeUpdateDataAttributes{}

// EmployeeUpdateDataAttributes struct for EmployeeUpdateDataAttributes
type EmployeeUpdateDataAttributes struct {
	// User role
	Role string `json:"role"`
}

type _EmployeeUpdateDataAttributes EmployeeUpdateDataAttributes

// NewEmployeeUpdateDataAttributes instantiates a new EmployeeUpdateDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmployeeUpdateDataAttributes(role string) *EmployeeUpdateDataAttributes {
	this := EmployeeUpdateDataAttributes{}
	this.Role = role
	return &this
}

// NewEmployeeUpdateDataAttributesWithDefaults instantiates a new EmployeeUpdateDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmployeeUpdateDataAttributesWithDefaults() *EmployeeUpdateDataAttributes {
	this := EmployeeUpdateDataAttributes{}
	return &this
}

// GetRole returns the Role field value
func (o *EmployeeUpdateDataAttributes) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *EmployeeUpdateDataAttributes) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *EmployeeUpdateDataAttributes) SetRole(v string) {
	o.Role = v
}

func (o EmployeeUpdateDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmployeeUpdateDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["role"] = o.Role
	return toSerialize, nil
}

func (o *EmployeeUpdateDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmployeeUpdateDataAttributes := _EmployeeUpdateDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmployeeUpdateDataAttributes)

	if err != nil {
		return err
	}

	*o = EmployeeUpdateDataAttributes(varEmployeeUpdateDataAttributes)

	return err
}

type NullableEmployeeUpdateDataAttributes struct {
	value *EmployeeUpdateDataAttributes
	isSet bool
}

func (v NullableEmployeeUpdateDataAttributes) Get() *EmployeeUpdateDataAttributes {
	return v.value
}

func (v *NullableEmployeeUpdateDataAttributes) Set(val *EmployeeUpdateDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableEmployeeUpdateDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableEmployeeUpdateDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmployeeUpdateDataAttributes(val *EmployeeUpdateDataAttributes) *NullableEmployeeUpdateDataAttributes {
	return &NullableEmployeeUpdateDataAttributes{value: val, isSet: true}
}

func (v NullableEmployeeUpdateDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmployeeUpdateDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


