/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DistributorEmployeeUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DistributorEmployeeUpdate{}

// DistributorEmployeeUpdate struct for DistributorEmployeeUpdate
type DistributorEmployeeUpdate struct {
	Data DistributorEmployeeUpdateData `json:"data"`
}

type _DistributorEmployeeUpdate DistributorEmployeeUpdate

// NewDistributorEmployeeUpdate instantiates a new DistributorEmployeeUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDistributorEmployeeUpdate(data DistributorEmployeeUpdateData) *DistributorEmployeeUpdate {
	this := DistributorEmployeeUpdate{}
	this.Data = data
	return &this
}

// NewDistributorEmployeeUpdateWithDefaults instantiates a new DistributorEmployeeUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDistributorEmployeeUpdateWithDefaults() *DistributorEmployeeUpdate {
	this := DistributorEmployeeUpdate{}
	return &this
}

// GetData returns the Data field value
func (o *DistributorEmployeeUpdate) GetData() DistributorEmployeeUpdateData {
	if o == nil {
		var ret DistributorEmployeeUpdateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DistributorEmployeeUpdate) GetDataOk() (*DistributorEmployeeUpdateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DistributorEmployeeUpdate) SetData(v DistributorEmployeeUpdateData) {
	o.Data = v
}

func (o DistributorEmployeeUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DistributorEmployeeUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DistributorEmployeeUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDistributorEmployeeUpdate := _DistributorEmployeeUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDistributorEmployeeUpdate)

	if err != nil {
		return err
	}

	*o = DistributorEmployeeUpdate(varDistributorEmployeeUpdate)

	return err
}

type NullableDistributorEmployeeUpdate struct {
	value *DistributorEmployeeUpdate
	isSet bool
}

func (v NullableDistributorEmployeeUpdate) Get() *DistributorEmployeeUpdate {
	return v.value
}

func (v *NullableDistributorEmployeeUpdate) Set(val *DistributorEmployeeUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableDistributorEmployeeUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableDistributorEmployeeUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDistributorEmployeeUpdate(val *DistributorEmployeeUpdate) *NullableDistributorEmployeeUpdate {
	return &NullableDistributorEmployeeUpdate{value: val, isSet: true}
}

func (v NullableDistributorEmployeeUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDistributorEmployeeUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


