/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmployeeCreateDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmployeeCreateDataAttributes{}

// EmployeeCreateDataAttributes struct for EmployeeCreateDataAttributes
type EmployeeCreateDataAttributes struct {
	Username string `json:"username"`
	// role for user
	Role string `json:"role"`
}

type _EmployeeCreateDataAttributes EmployeeCreateDataAttributes

// NewEmployeeCreateDataAttributes instantiates a new EmployeeCreateDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmployeeCreateDataAttributes(username string, role string) *EmployeeCreateDataAttributes {
	this := EmployeeCreateDataAttributes{}
	this.Username = username
	this.Role = role
	return &this
}

// NewEmployeeCreateDataAttributesWithDefaults instantiates a new EmployeeCreateDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmployeeCreateDataAttributesWithDefaults() *EmployeeCreateDataAttributes {
	this := EmployeeCreateDataAttributes{}
	return &this
}

// GetUsername returns the Username field value
func (o *EmployeeCreateDataAttributes) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *EmployeeCreateDataAttributes) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *EmployeeCreateDataAttributes) SetUsername(v string) {
	o.Username = v
}

// GetRole returns the Role field value
func (o *EmployeeCreateDataAttributes) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *EmployeeCreateDataAttributes) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *EmployeeCreateDataAttributes) SetRole(v string) {
	o.Role = v
}

func (o EmployeeCreateDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmployeeCreateDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["username"] = o.Username
	toSerialize["role"] = o.Role
	return toSerialize, nil
}

func (o *EmployeeCreateDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"username",
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmployeeCreateDataAttributes := _EmployeeCreateDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmployeeCreateDataAttributes)

	if err != nil {
		return err
	}

	*o = EmployeeCreateDataAttributes(varEmployeeCreateDataAttributes)

	return err
}

type NullableEmployeeCreateDataAttributes struct {
	value *EmployeeCreateDataAttributes
	isSet bool
}

func (v NullableEmployeeCreateDataAttributes) Get() *EmployeeCreateDataAttributes {
	return v.value
}

func (v *NullableEmployeeCreateDataAttributes) Set(val *EmployeeCreateDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableEmployeeCreateDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableEmployeeCreateDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmployeeCreateDataAttributes(val *EmployeeCreateDataAttributes) *NullableEmployeeCreateDataAttributes {
	return &NullableEmployeeCreateDataAttributes{value: val, isSet: true}
}

func (v NullableEmployeeCreateDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmployeeCreateDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


