openapi: 3.1.0
info:
  description: Title
  title: Title
  version: 1.0.0
servers:
- url: /
paths:
  /test:
    post:
      operationId: Test
      responses:
        "201":
          description: Created
      summary: Test
components:
  schemas:
    Distributor:
      properties:
        data:
          $ref: '#/components/schemas/Distributor_data'
      required:
      - data
    DistributorUpdate:
      properties:
        data:
          $ref: '#/components/schemas/DistributorUpdate_data'
      required:
      - data
    DistributorCreate:
      properties:
        data:
          $ref: '#/components/schemas/DistributorCreate_data'
      required:
      - data
    DistributorEmployee:
      properties:
        data:
          $ref: '#/components/schemas/DistributorEmployee_data'
      required:
      - data
    DistributorEmployeeCreate:
      properties:
        data:
          $ref: '#/components/schemas/DistributorEmployeeCreate_data'
      required:
      - data
    DistributorEmployeeUpdate:
      properties:
        data:
          $ref: '#/components/schemas/DistributorEmployeeUpdate_data'
      required:
      - data
    DistributorEmployeeDelete:
      properties:
        data:
          $ref: '#/components/schemas/DistributorEmployeeDelete_data'
      required:
      - data
    DistributorEmployeeCollection:
      properties:
        data:
          $ref: '#/components/schemas/DistributorEmployeeCollection_data'
      required:
      - data
    PlaceEmployee:
      properties:
        data:
          $ref: '#/components/schemas/PlaceEmployee_data'
      required:
      - data
    PlaceEmployeeCollection:
      properties:
        data:
          $ref: '#/components/schemas/PlaceEmployeeCollection_data'
      required:
      - data
    PlaceEmployeeCreate:
      properties:
        data:
          $ref: '#/components/schemas/PlaceEmployeeCreate_data'
      required:
      - data
    PlaceEmployeeUpdate:
      properties:
        data:
          $ref: '#/components/schemas/PlaceEmployeeUpdate_data'
      required:
      - data
    Distributor_data_attributes:
      properties:
        name:
          description: Distributor name
          type: string
        owner_id:
          description: Owner ID
          type: string
      required:
      - name
      - owner_id
    Distributor_data:
      properties:
        id:
          description: distributor ID
          type: string
        type:
          enum:
          - distributor
          type: string
        attributes:
          $ref: '#/components/schemas/Distributor_data_attributes'
      required:
      - attributes
      - id
      - type
    DistributorUpdate_data_attributes:
      properties:
        name:
          description: Distributor name
          type: string
      required:
      - name
    DistributorUpdate_data:
      properties:
        type:
          enum:
          - distributor_update
          type: string
        attributes:
          $ref: '#/components/schemas/DistributorUpdate_data_attributes'
      required:
      - attributes
      - type
    DistributorCreate_data:
      properties:
        type:
          enum:
          - distributor_create
          type: string
        attributes:
          $ref: '#/components/schemas/DistributorUpdate_data_attributes'
      required:
      - attributes
      - type
    DistributorEmployee_data_attributes:
      properties:
        user_id:
          description: User ID
          type: string
        role:
          description: User role
          type: string
        distributor_id:
          description: Distributor ID
          type: string
        created_at:
          description: Creation date
          format: date-time
          type: string
      required:
      - created_at
      - distributor_id
      - role
      - user_id
    DistributorEmployee_data:
      properties:
        id:
          description: employee ID
          type: string
        type:
          enum:
          - distributor_employee
          type: string
        attributes:
          $ref: '#/components/schemas/DistributorEmployee_data_attributes'
      required:
      - attributes
      - id
      - type
    DistributorEmployeeCreate_data_attributes:
      properties:
        username:
          type: string
        role:
          description: role for user
          type: string
      required:
      - role
      - username
    DistributorEmployeeCreate_data:
      properties:
        type:
          enum:
          - distributor_employee_create
          type: string
        attributes:
          $ref: '#/components/schemas/DistributorEmployeeCreate_data_attributes'
      required:
      - attributes
      - type
    DistributorEmployeeUpdate_data_attributes:
      properties:
        role:
          description: User role
          type: string
      required:
      - role
    DistributorEmployeeUpdate_data:
      properties:
        type:
          enum:
          - distributor_employee_update
          type: string
        attributes:
          $ref: '#/components/schemas/DistributorEmployeeUpdate_data_attributes'
      required:
      - attributes
      - type
    DistributorEmployeeDelete_data_attributes:
      properties:
        user_id:
          description: User ID
          type: string
      required:
      - user_id
    DistributorEmployeeDelete_data:
      properties:
        type:
          enum:
          - distributor_employee_delete
          type: string
        attributes:
          $ref: '#/components/schemas/DistributorEmployeeDelete_data_attributes'
      required:
      - attributes
      - type
    DistributorEmployeeCollection_data_attributes_inner:
      properties:
        data:
          $ref: '#/components/schemas/DistributorEmployee_data'
      required:
      - data
    DistributorEmployeeCollection_data:
      properties:
        type:
          enum:
          - distributor_employee_collection
          type: string
        attributes:
          items:
            $ref: '#/components/schemas/DistributorEmployeeCollection_data_attributes_inner'
          type: array
      required:
      - attributes
      - type
    PlaceEmployee_data_attributes:
      properties:
        user_id:
          description: User ID
          type: string
        place_id:
          description: Place ID
          type: string
        employee_id:
          description: Employee ID
          type: string
        username:
          description: Username
          type: string
        role:
          description: User role
          type: string
        created_at:
          description: Creation date
          format: date-time
          type: string
        updated_at:
          description: Update date
          format: date-time
          type: string
      required:
      - created_at
      - employee_id
      - place_id
      - role
      - updated_at
      - user_id
      - username
    PlaceEmployee_data:
      properties:
        id:
          description: employee ID
          type: string
        type:
          enum:
          - place_employee
          type: string
        attributes:
          $ref: '#/components/schemas/PlaceEmployee_data_attributes'
      required:
      - attributes
      - id
      - type
    PlaceEmployeeCollection_data_attributes_inner:
      properties:
        data:
          $ref: '#/components/schemas/PlaceEmployee_data'
      required:
      - data
    PlaceEmployeeCollection_data:
      properties:
        type:
          enum:
          - place_employee_collection
          type: string
        attributes:
          items:
            $ref: '#/components/schemas/PlaceEmployeeCollection_data_attributes_inner'
          type: array
      required:
      - attributes
      - type
    PlaceEmployeeCreate_data_attributes:
      properties:
        username:
          type: string
        role:
          description: role for user
          type: string
        distributor_id:
          description: Distributor ID
          type: string
      required:
      - distributor_id
      - role
      - username
    PlaceEmployeeCreate_data:
      properties:
        type:
          enum:
          - place_employee_create
          type: string
        attributes:
          $ref: '#/components/schemas/PlaceEmployeeCreate_data_attributes'
      required:
      - attributes
      - type
    PlaceEmployeeUpdate_data_attributes:
      properties:
        role:
          description: User role
          type: string
        distributor_id:
          description: Distributor ID
          type: string
      required:
      - distributor_id
      - role
    PlaceEmployeeUpdate_data:
      properties:
        type:
          enum:
          - place_employee_update
          type: string
        attributes:
          $ref: '#/components/schemas/PlaceEmployeeUpdate_data_attributes'
      required:
      - attributes
      - type
