openapi: 3.1.0
info:
  description: Title
  title: Title
  version: 1.0.0
servers:
- url: /
paths:
  /test:
    post:
      operationId: Test
      responses:
        "201":
          description: Created
      summary: Test
components:
  schemas:
    Distributor:
      properties:
        data:
          $ref: '#/components/schemas/Distributor_data'
      required:
      - data
    DistributorUpdate:
      properties:
        data:
          $ref: '#/components/schemas/DistributorUpdate_data'
      required:
      - data
    DistributorCreate:
      properties:
        data:
          $ref: '#/components/schemas/DistributorCreate_data'
      required:
      - data
    Employee:
      properties:
        data:
          $ref: '#/components/schemas/Employee_data'
      required:
      - data
    EmployeeCreate:
      properties:
        data:
          $ref: '#/components/schemas/EmployeeCreate_data'
      required:
      - data
    EmployeeUpdate:
      properties:
        data:
          $ref: '#/components/schemas/EmployeeUpdate_data'
      required:
      - data
    EmployeeDelete:
      properties:
        data:
          $ref: '#/components/schemas/EmployeeDelete_data'
      required:
      - data
    EmployeeCollection:
      properties:
        data:
          $ref: '#/components/schemas/EmployeeCollection_data'
      required:
      - data
    Distributor_data_attributes:
      properties:
        name:
          description: Distributor name
          type: string
        owner_id:
          description: Owner ID
          type: string
      required:
      - name
      - owner_id
    Distributor_data:
      properties:
        id:
          description: distributor ID
          type: string
        type:
          enum:
          - distributor
          type: string
        attributes:
          $ref: '#/components/schemas/Distributor_data_attributes'
      required:
      - attributes
      - id
      - type
    DistributorUpdate_data_attributes:
      properties:
        name:
          description: Distributor name
          type: string
      required:
      - name
    DistributorUpdate_data:
      properties:
        type:
          enum:
          - distributor_update
          type: string
        attributes:
          $ref: '#/components/schemas/DistributorUpdate_data_attributes'
      required:
      - attributes
      - type
    DistributorCreate_data:
      properties:
        type:
          enum:
          - distributor_create
          type: string
        attributes:
          $ref: '#/components/schemas/DistributorUpdate_data_attributes'
      required:
      - attributes
      - type
    Employee_data_attributes:
      properties:
        user_id:
          description: User ID
          type: string
        role:
          description: User role
          type: string
        distributor_id:
          description: Distributor ID
          type: string
        created_at:
          description: Creation date
          format: date-time
          type: string
      required:
      - created_at
      - distributor_id
      - role
      - user_id
    Employee_data:
      properties:
        id:
          description: employee ID
          type: string
        type:
          enum:
          - distributor_employee
          type: string
        attributes:
          $ref: '#/components/schemas/Employee_data_attributes'
      required:
      - attributes
      - id
      - type
    EmployeeCreate_data_attributes:
      properties:
        user_id:
          description: User ID
          type: string
        role:
          description: User role
          type: string
        created_at:
          description: Creation date
          format: date-time
          type: string
      required:
      - created_at
      - role
      - user_id
    EmployeeCreate_data:
      properties:
        type:
          enum:
          - distributor_employee_create
          type: string
        attributes:
          $ref: '#/components/schemas/EmployeeCreate_data_attributes'
      required:
      - attributes
      - type
    EmployeeUpdate_data_attributes:
      properties:
        role:
          description: User role
          type: string
      required:
      - role
    EmployeeUpdate_data:
      properties:
        id:
          description: Resource ID
          type: string
        type:
          enum:
          - distributor_employee_update
          type: string
        attributes:
          $ref: '#/components/schemas/EmployeeUpdate_data_attributes'
      required:
      - attributes
      - id
      - type
    EmployeeDelete_data_attributes:
      properties:
        user_id:
          description: User ID
          type: string
      required:
      - user_id
    EmployeeDelete_data:
      properties:
        type:
          enum:
          - distributor_employee_delete
          type: string
        attributes:
          $ref: '#/components/schemas/EmployeeDelete_data_attributes'
      required:
      - attributes
      - type
    EmployeeCollection_data_attributes_inner:
      properties:
        data:
          $ref: '#/components/schemas/Employee_data'
      required:
      - data
    EmployeeCollection_data:
      properties:
        type:
          enum:
          - distributor_employee_collection
          type: string
        attributes:
          items:
            $ref: '#/components/schemas/EmployeeCollection_data_attributes_inner'
          type: array
      required:
      - attributes
      - type
