openapi: 3.1.0
info:
  title: Title
  description: Title
  version: 1.0.0


paths:
  /test:
    post:
      summary: Test
      operationId: Test
      responses:
        '201':
          description: Created

components:
  schemas:
    Distributor:
      $ref: './spec/components/schemas/Distributor.yaml'
    DistributorUpdate:
      $ref: './spec/components/schemas/DistributorUpdate.yaml'
    DistributorCreate:
      $ref: './spec/components/schemas/DistributorCreate.yaml'
    DistributorEmployee:
      $ref: './spec/components/schemas/DistributorEmployee.yaml'
    DistributorEmployeeCreate:
      $ref: './spec/components/schemas/DistributorEmployeeCreate.yaml'
    DistributorEmployeeUpdate:
      $ref: './spec/components/schemas/DistributorEmployeeUpdate.yaml'
    DistributorEmployeeDelete:
      $ref: './spec/components/schemas/DistributorEmployeeDelete.yaml'
    DistributorEmployeeCollection:
      $ref: './spec/components/schemas/DistributorEmployeeCollection.yaml'
    PlaceEmployee:
      $ref: './spec/components/schemas/PlaceEmployee.yaml'
    PlaceEmployeeCollection:
      $ref: './spec/components/schemas/PlaceEmployeeCollection.yaml'
    PlaceEmployeeCreate:
      $ref: './spec/components/schemas/PlaceEmployeeCreate.yaml'
    PlaceEmployeeUpdate:
      $ref: './spec/components/schemas/PlaceEmployeeUpdate.yaml'
